import os
import requests
from dotenv import load_dotenv

load_dotenv()

# Centralized configuration
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
DEFAULT_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
DEFAULT_TEMP = float(os.getenv("LLM_TEMP", "0.3"))
DEFAULT_MAX_TOKENS = int(os.getenv("LLM_MAX_TOKENS", "2048"))

# Reusable HTTP session for connection pooling
session = requests.Session()
session.headers.update({
    "Authorization": f"Bearer {GROQ_API_KEY}",
    "Content-Type": "application/json"
})

def generate_answer(prompt: str) -> str:
    """Generate answer using Groq API with connection reuse"""
    if not GROQ_API_KEY:
        return "Please configure GROQ_API_KEY in your .env file"
    
    try:
        payload = {
            "model": DEFAULT_MODEL,
            "messages": [
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            "temperature": DEFAULT_TEMP,
            "max_tokens": DEFAULT_MAX_TOKENS
        }
        
        response = session.post(GROQ_API_URL, json=payload, timeout=30)
        
        if response.status_code == 200:
            data = response.json()
            choices = data.get("choices", [])
            if not choices:
                return "No response generated by model."
            return choices[0].get("message", {}).get("content", "")
        else:
            return f"Error: {response.status_code} - {response.text}"
            
    except Exception as e:
        print(f"Groq API error: {e}")
        return "Unable to generate answer. Please check your API key and connection."


def generate_summary(prompt: str) -> str:
    """Generate summary using Groq API"""
    return generate_answer(prompt)

